stages:
    - build_and_push
    
variables:
    HARBOR_REPOSITORY: tupperware.mynt.xyz/datascience/innovations/project-chatdpt
    
before_script:
    - env
    
docker build image:
    stage: build_and_push
    before_script:
    - docker login -u ${MLOPS_TPW_SA_USERNAME} -p ${MLOPS_TPW_SA_PASSWORD} tupperware.mynt.xyz
    script:
    - docker build --platform linux/amd64 --tag $HARBOR_REPOSITORY:latest --tag $HARBOR_REPOSITORY:$CI_COMMIT_TAG .
    - docker push $HARBOR_REPOSITORY:latest
    - docker push $HARBOR_REPOSITORY:$CI_COMMIT_TAG
