"""added chat foreign key

Revision ID: 6bc9468990f3
Revises: 21b201e3836e
Create Date: 2023-06-30 09:52:59.491356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc9468990f3'
down_revision = '21b201e3836e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
