"""added chats

Revision ID: 88c4bf2dcc28
Revises: 2df721d5b4e0
Create Date: 2023-06-29 10:48:16.822507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c4bf2dcc28'
down_revision = '2df721d5b4e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
