"""added chats

Revision ID: fcc13e0fadea
Revises: 3019d296f8f3
Create Date: 2023-06-29 10:13:58.384308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc13e0fadea'
down_revision = '3019d296f8f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
